// ActionUI - SwiftUI component library
// Copyright (c) 2025-2026 Tomasz Kukielka
//
// Licensed under the PolyForm Small Business License 1.0.0
// https://polyformproject.org/licenses/small-business/1.0.0

//
//  ActionUIC.h
//  ActionUICAdapter
//
//  C interface for ActionUI, enabling integration with C-based languages.
//  Part of the ActionUI project - provides a dynamic framework for C bindings.
//
//  NOTE: This header defines TYPES only (enums, callback typedefs).
//  Function declarations are auto-generated by the Swift compiler in
//  ActionUICAdapter-Swift.h, which is guarded with #if defined(__OBJC__).
//
//  Clients must compile their source as Objective-C (.m extension) so that
//  Clang defines __OBJC__ automatically, entering the generated header's
//  declaration block naturally.  The source code itself can be plain C;
//  only the compilation mode needs to be Objective-C.  See BUILD.md.
//
//  Bool types: @_cdecl functions use Swift's CBool (= C stdbool.h bool)
//  for all boolean parameters and return values, so the generated header
//  emits `bool` rather than ObjC's `BOOL` (which is `signed char` on x86_64).
//

#ifndef ActionUIC_h
#define ActionUIC_h

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

// MARK: - Logging

/// Log levels matching ActionUI.LoggerLevel
typedef enum {
    ActionUILogLevelError   = 1,
    ActionUILogLevelWarning = 2,
    ActionUILogLevelInfo    = 3,
    ActionUILogLevelDebug   = 4,
    ActionUILogLevelVerbose = 5
} ActionUILogLevel;

/// Logger callback function type.
/// Parameters: message (null-terminated UTF-8 C string), level
typedef void (*ActionUILoggerCallback)(const char* message, ActionUILogLevel level);

// MARK: - Action Handling

/// Action handler callback function type.
/// Parameters: actionID, windowUUID, viewID, viewPartID, contextJSON (nullable)
typedef void (*ActionUIActionHandler)(const char* actionID,
                                      const char* windowUUID,
                                      int64_t     viewID,
                                      int64_t     viewPartID,
                                      const char* contextJSON);

// MARK: - Modal Presentation

/// Modal presentation style.
typedef enum {
    ActionUIModalStyleSheet           = 0,
    ActionUIModalStyleFullScreenCover = 1
} ActionUIModalStyle;

/// Button role for dialog buttons.
typedef enum {
    ActionUIButtonRoleDefault     = 0,  ///< Normal prominence (no special role)
    ActionUIButtonRoleCancel      = 1,  ///< Cancel action
    ActionUIButtonRoleDestructive = 2   ///< Destructive action (red tint)
} ActionUIButtonRole;

#ifdef __cplusplus
}
#endif

#endif /* ActionUIC_h */
