// ActionUI - SwiftUI component library
// Copyright (c) 2025-2026 Tomasz Kukielka
//
// Licensed under the PolyForm Small Business License 1.0.0
// https://polyformproject.org/licenses/small-business/1.0.0

//
//  ActionUIApp.h
//  ActionUIAppKitApplication
//
//  C types for the AppKit application lifecycle adapter.
//
//  NOTE: This header defines TYPES only.
//  Function declarations are auto-generated by the Swift compiler in
//  ActionUIAppKitApplication-Swift.h, guarded with #if defined(__OBJC__).
//  Clients must compile as Objective-C (.m) so __OBJC__ is defined
//  automatically.  See ActionUIPython/BUILD.md.
//
//  Bool: all @_cdecl functions use Swift's CBool (= stdbool.h bool).
//

#ifndef ActionUIApp_h
#define ActionUIApp_h

#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

// MARK: - App lifecycle callbacks

/// No-argument void callback used for all simple lifecycle events.
typedef void (*ActionUIAppLifecycleHandler)(void);

/// Return true to allow termination, false to cancel.
typedef bool (*ActionUIAppShouldTerminateHandler)(void);

// MARK: - Window callbacks

/// Fired when a tracked window is about to close.
/// windowUUID — the UUID that was passed to actionUIAppLoadAndPresentWindow.
typedef void (*ActionUIAppWindowHandler)(const char* windowUUID);

#ifdef __cplusplus
}
#endif

#endif /* ActionUIApp_h */
