#!/usr/bin/env python3
"""
ActionUI Skill Builder
======================
Reads Skill/master/skill.meta.json and Skill/master/content/*.md, then assembles
flavor-specific SKILL.md files and packages them with the Python verifier.

Usage:
    python3 Skill/build_skill.py                    # build all flavors + master SKILL.md
    python3 Skill/build_skill.py --flavor claude     # build one flavor only
    python3 Skill/build_skill.py --master-only       # regenerate Skill/SKILL.md only

Output:
    Skill/SKILL.md                   — claude flavor (primary dev reference)
    Skill/dist/claude/SKILL.md       — packaged claude flavor with verifier
    Skill/dist/capable/SKILL.md      — capable-model flavor (Gemini, Grok, GPT-4o, ...)
    Skill/dist/lite/SKILL.md         — lite/local model flavor
"""

import argparse
import json
import re
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
MASTER_DIR = REPO_ROOT / "Skill" / "master"
CONTENT_DIR = MASTER_DIR / "content"
META_FILE = MASTER_DIR / "skill.meta.json"
VERIFIER_SRC = REPO_ROOT / "Tools" / "verifier"
SKILL_MAIN = REPO_ROOT / "Skill" / "SKILL.md"


# ── YAML front-matter parsing (no external deps) ──────────────────────────────

def parse_frontmatter(text: str) -> tuple[dict, str]:
    """Split YAML front-matter from markdown body. Returns (meta, body)."""
    if not text.startswith("---"):
        return {}, text
    end = text.find("\n---", 3)
    if end == -1:
        return {}, text
    fm_block = text[3:end].strip()
    body = text[end + 4:].lstrip("\n")
    meta = {}
    for line in fm_block.splitlines():
        if ":" in line:
            k, _, v = line.partition(":")
            v = v.strip()
            if v.startswith("[") and v.endswith("]"):
                items = [i.strip() for i in v[1:-1].split(",")]
                meta[k.strip()] = items
            else:
                meta[k.strip()] = v
    return meta, body


# ── Content loading ───────────────────────────────────────────────────────────

def load_content_pieces(meta: dict) -> dict[str, tuple[dict, str]]:
    """Return {content_id: (frontmatter, body)} for all declared content."""
    pieces = {}
    for entry in meta["content"]:
        filename = Path(entry["file"]).name
        path = CONTENT_DIR / filename
        if not path.exists():
            print(f"[WARN] content file not found: {path}", file=sys.stderr)
            continue
        text = path.read_text(encoding="utf-8")
        fm, body = parse_frontmatter(text)
        pieces[entry["id"]] = (fm, body)
    return pieces


# ── Flavor-specific transformations ──────────────────────────────────────────

def apply_transforms(body: str, content_id: str, flavor: str, flavor_cfg: dict) -> str:
    """Apply per-flavor transformations to a content piece body."""
    # Validation section: adapt script-execution instruction for non-script flavors
    if content_id == "validation" and not flavor_cfg.get("script_execution", True):
        body = body.replace(
            "```bash\npython3 Skill/scripts/validate_actionui.py <file-or-directory>\n```",
            "```bash\n# If you have Python available:\npython3 validate_actionui.py <file>\n```\n\n"
            "If you cannot run scripts, manually verify: no duplicate `id` values, "
            "all property names match the element schema, all required fields present."
        )

    # Lite: strip Markdown tables (replace with brief prose)
    if flavor_cfg.get("format") == "markdown":
        body = _strip_tables(body)

    return body


def _strip_tables(text: str) -> str:
    """Remove Markdown tables, preserving the heading above each table."""
    lines = text.splitlines()
    result = []
    i = 0
    while i < len(lines):
        line = lines[i]
        # Detect table header row (contains | and next line is separator)
        if "|" in line and i + 1 < len(lines) and re.match(r"^\|[-| :]+\|", lines[i + 1]):
            # Skip the entire table block
            while i < len(lines) and "|" in lines[i]:
                i += 1
            result.append("*(see schema files for full reference)*")
        else:
            result.append(line)
            i += 1
    return "\n".join(result)


# ── Assembly ──────────────────────────────────────────────────────────────────

def _build_description(meta: dict, flavor: str, flavor_cfg: dict) -> str:
    """Build the description field, appending trigger keywords for lite flavor."""
    base = meta["description"]
    triggers = flavor_cfg.get("triggers", [])
    if triggers:
        kw = ", ".join(triggers)
        return f"{base}\nKeywords: {kw}"
    return base


HEADER_TEMPLATE = """\
---
name: {name}
description: >
  {description}
version: "{version}"
---

# ActionUI Skill
"""

FOOTER = "*Generated by Skill/build_skill.py — edit Skill/master/content/*.md, not this file.*"


def assemble(meta: dict, pieces: dict, flavor: str) -> str:
    """Assemble a SKILL.md string for the given flavor."""
    flavor_cfg = meta["flavors"][flavor]
    max_levels = flavor_cfg["disclosure_levels"]
    description = _build_description(meta, flavor, flavor_cfg)

    parts = [HEADER_TEMPLATE.format(
        name=meta["name"],
        description=description,
        version=meta["version"],
    )]

    for entry in meta["content"]:
        cid = entry["id"]
        if flavor not in entry["flavors"]:
            continue
        if entry["level"] not in max_levels:
            continue
        if cid not in pieces:
            continue
        _fm, body = pieces[cid]
        body = apply_transforms(body, cid, flavor, flavor_cfg)
        parts.append(body.strip())
        parts.append("")

    parts.append(FOOTER)
    return "\n\n".join(parts) + "\n"


# ── Distribution packaging ────────────────────────────────────────────────────

def _copy_docs(meta: dict, docs_out: Path) -> None:
    """Copy Documentation/ reference material into docs/ inside the dist flavor."""
    docs_src_rel = meta["build"].get("docs_source")
    if not docs_src_rel:
        return
    docs_src = REPO_ROOT / docs_src_rel

    if docs_out.exists():
        shutil.rmtree(docs_out)
    docs_out.mkdir()

    for name in ["ActionUI-Elements.md", "ActionUI-JSON-Guide.md", "ActionUI-MenuBar-JSON-Guide.md"]:
        src = docs_src / name
        if src.exists():
            shutil.copy2(src, docs_out / name)

    for subdir in ["Schemas", "Elements"]:
        src = docs_src / subdir
        if src.exists():
            shutil.copytree(src, docs_out / subdir)


def package_flavor(meta: dict, skill_md: str, flavor: str) -> None:
    """Write SKILL.md + verifier + docs into Skill/dist/<flavor>/."""
    out_dir = REPO_ROOT / "Skill" / "dist" / flavor
    scripts_out = out_dir / "scripts"
    docs_out = out_dir / "docs"
    out_dir.mkdir(parents=True, exist_ok=True)
    scripts_out.mkdir(parents=True, exist_ok=True)

    (out_dir / "SKILL.md").write_text(skill_md, encoding="utf-8")

    for item in VERIFIER_SRC.iterdir():
        src = VERIFIER_SRC / item.name
        dst = scripts_out / item.name
        if src.is_dir():
            if dst.exists():
                shutil.rmtree(dst)
            shutil.copytree(src, dst)
        else:
            shutil.copy2(src, dst)

    _copy_docs(meta, docs_out)

    print(f"  [{flavor}] → {out_dir}")


# ── CLI ───────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(description="ActionUI Skill Builder")
    parser.add_argument("--flavor", choices=["claude", "capable", "lite"],
                        help="Build a single flavor only")
    parser.add_argument("--master-only", action="store_true",
                        help="Regenerate Skill/SKILL.md (claude flavor) only; skip dist packaging")
    args = parser.parse_args()

    if not META_FILE.exists():
        print(f"error: {META_FILE} not found", file=sys.stderr)
        sys.exit(1)

    meta = json.loads(META_FILE.read_text(encoding="utf-8"))
    pieces = load_content_pieces(meta)

    missing = [e["id"] for e in meta["content"] if e["id"] not in pieces]
    if missing:
        print(f"[WARN] missing content pieces: {missing}", file=sys.stderr)

    if args.master_only:
        skill_md = assemble(meta, pieces, "claude")
        SKILL_MAIN.write_text(skill_md, encoding="utf-8")
        print(f"  [master] → {SKILL_MAIN}")
        print("Done.")
        return

    flavors_to_build = [args.flavor] if args.flavor else list(meta["flavors"].keys())

    print("Building skill flavors…")
    for flavor in flavors_to_build:
        skill_md = assemble(meta, pieces, flavor)
        if flavor == "claude":
            SKILL_MAIN.write_text(skill_md, encoding="utf-8")
            print(f"  [master] → {SKILL_MAIN}")
        package_flavor(meta, skill_md, flavor)

    print("Done.")


if __name__ == "__main__":
    main()
