// ActionUI - SwiftUI component library
// Copyright (c) 2025-2026 Tomasz Kukielka
//
// Licensed under the PolyForm Small Business License 1.0.0
// https://polyformproject.org/licenses/small-business/1.0.0

//
//  ActionUIC.h
//  ActionUICAdapter
//
//  C interface for ActionUI, enabling integration with C-based languages.
//  Part of the ActionUI project - provides static framework for C bindings.
//
//  NOTE: This header defines TYPES only (enums, typedefs, function pointer types).
//  Function DECLARATIONS are auto-generated by Xcode in ActionUICAdapter-Swift.h
//  (but only when __OBJC__ is defined)
//

#ifndef ActionUIC_h
#define ActionUIC_h

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

// MARK: - Logging

/// Log levels matching ActionUI.LoggerLevel
typedef enum {
    ActionUILogLevelError = 1,
    ActionUILogLevelWarning = 2,
    ActionUILogLevelInfo = 3,
    ActionUILogLevelDebug = 4,
    ActionUILogLevelVerbose = 5
} ActionUILogLevel;

/// Logger callback function type
/// Parameters: message (C string), level (ActionUILogLevel)
typedef void (*ActionUILoggerCallback)(const char* message, ActionUILogLevel level);

// MARK: - Action Handling

/// Action handler callback function type
/// Parameters: actionID, windowUUID, viewID, viewPartID, contextJSON (nullable C string)
typedef void (*ActionUIActionHandler)(const char* actionID,
                                      const char* windowUUID,
                                      int64_t viewID,
                                      int64_t viewPartID,
                                      const char* contextJSON);

#ifdef __cplusplus
}
#endif

#endif /* ActionUIC_h */
